Use pug for build page
Dreikk2131/node_js pull request #6
Opened 2018-11-06 12:40 UTC by Dreikk2131

2018-11-06 17:09 UTC, dimitriirybakov requested changes

2018-11-06 17:09 UTC, dimitriirybakov commented on index.js
> +app.use(express.static(__dirname + '/pugF'));
Зачем? Тебе же не нужны шаблоны на клиенте. А css оставь в static

2018-11-06 17:09 UTC, dimitriirybakov commented on pugF/change_page.css
> +body{
А почему тогда старые эти файлы (css, image) не удалил из static? Зачем две копии одного и того же?
Но вообще оставь в static а эти удали
здесь должны быть только шаблоны

2018-11-06 17:09 UTC, dimitriirybakov commented on pugF/change_page.pug
> +        include header
Молодец что сделал так, но тут лучше подходит https://pugjs.org/language/inheritance.html. И в layout вынести все что общее (то есть head и все такое). Но по факту ничего поменяться не должно (в браузере в смысле)

2018-11-06 17:09 UTC, dimitriirybakov commented on pugF/start.pug
> +    section(class='content')
У тебя во многих местах остались class. Зачем? Можно же `section.content`

2018-11-06 17:09 UTC, dimitriirybakov commented on pugF/start.pug
> +        div(class='content-for')
ненужный div

2018-11-06 17:09 UTC, dimitriirybakov commented on pugF/start.pug
> +        div(class='content-for')
и каждый блок чтобы не повторять одну и ту же верстку лучше вынести в mixin https://pugjs.org/language/mixins.html

2018-11-07 05:01 UTC, Dreikk2131 commented on pugF/start.pug
> +    section(class='content')
Я знаю что можно, просто мне так наглядней. Если я писал класс рядом с тегом я специально выносил его в скобках

2018-11-07 05:30 UTC, Dreikk2131 commented on index.js
> +app.use(express.static(__dirname + '/pugF'));
CSS перенес в static. Фраза "шаблоны на клиенте" не понимаю

2018-11-07 05:30 UTC, dimitriirybakov commented on pugF/start.pug
> +    section(class='content')
Ну так менее правильно
у тебя в одном месте класс через точку, в другом через class
нужно стараться чтобы у тебя во всем было все одинаково

2018-11-07 05:34 UTC, dimitriirybakov commented on index.js
> +app.use(express.static(__dirname + '/pugF'));
Ну pug файлы это же не html 
Это называется шаблонами, из них получается html
Но ты отдаешь шаблоны на клиент. Они ж там не нужны

2018-11-07 05:36 UTC, Dreikk2131 commented on pugF/start.pug
> +    section(class='content')
Исправил

2018-11-07 05:36 UTC, Dreikk2131 commented on pugF/change_page.css
> +body{
Исправил

2018-11-07 09:43 UTC, Dreikk2131 commented
Почему я не могу в start заменить код 
div.content-for
            .content-text
на mixin? он выдает самые разнообразные ошибки, но не работает
При этом кнопку же удалось сделать

2018-11-08 08:57 UTC, dimitriirybakov requested changes
переименуй pugF во views

2018-11-08 08:57 UTC, dimitriirybakov commented on pugF/start.pug
> +mixin recipe(ob)
назови переменную recipe тоже, а то что за ob

2018-11-08 08:57 UTC, dimitriirybakov commented on pugF/start.pug
> +            img(src= ''+ob.adress, alt= ''+ob.add)
зачем ''+ ?

2018-11-08 08:57 UTC, dimitriirybakov commented on pugF/start.pug
> +        +button
а этот миксин особо не нужен теперь

2018-11-08 08:57 UTC, dimitriirybakov commented on pugF/vars.pug
> +-
это все можно наверное в start.pug оставить, все равно это временное

2018-11-08 08:57 UTC, dimitriirybakov commented on pugF/vars.pug
> +-
А лучше перенести на сервер и передавать в шаблон как параметр

2018-11-08 09:32 UTC, Dreikk2131 commented on pugF/vars.pug
> +-
последнее что то сложное, не понимаю как этот файл перенести параметром. Его res.render налету соберет?

2018-11-08 09:41 UTC, dimitriirybakov commented on pugF/vars.pug
> +-
Зачем файл. Просто список объектов передавать в render

2018-11-08 11:30 UTC, Dreikk2131 commented on pugF/vars.pug
> +-
все равно не понимаю, он пишет, что передавать можно только строку, а я ему тут обьект пытаюсь втюхать

2018-11-12 06:00 UTC, dimitriirybakov requested changes

2018-11-12 06:00 UTC, dimitriirybakov commented on .gitignore
> +views/examle2.pug
зачем это сюда добавлять?
и example.js тоже

2018-11-12 06:00 UTC, dimitriirybakov commented on index.js
> +  res.render('start', {rec1, rec2, rec3, rec4});
почему не массивом?

2018-11-12 06:00 UTC, dimitriirybakov commented on static/main.css
> +.head-brand a{
А почему у тебя куча одного и того же css в разных файлах?
Вынеси общее в отдельный и используй его везде.
common.css назови

2018-11-12 06:00 UTC, dimitriirybakov commented on views/start.pug
> +        +recipe(rec1)
и если бы был список, то можно было бы тут тоже циклом пройтись

2018-11-12 06:00 UTC, dimitriirybakov commented on views/vars.pug
> +-
вот это удалить же нужно

2018-11-12 06:00 UTC, dimitriirybakov commented on index.js
> +  res.render('start', {rec1, rec2, rec3, rec4});
а сверху вместо 4 объектов объявить массив recipes

```res.render('start', {recipes});```

2018-11-13 05:07 UTC, merged